routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('transactions', 'PaymentController');
    Route::get('/account', 'DashboardController@editAccount')->name('edit.account');
    Route::post('/update', 'DashboardController@accountUpdate')->name('account.update');
});

//Account
Route::group(['prefix' => 'pages', 'middleware' => 'auth'], function() {
    Route::get('/deposit-funds', 'HomeController@refill')->name('refill');
    Route::get('/transfer/wallet', 'HomeController@transaction')->name('transaction');
    Route::get('/transaction', 'HomeController@historyTransactions')->name('history.transactions');
});
    Route::post('/show_more', 'HomeController@show_more');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;


use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }

    public function editAccount()
    {
        $user = auth()->user();

        return view('dashboard.account.index', compact('user'));
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Throwable
     */
    public function accountUpdate(Request $request)
    {
        DB::beginTransaction();
        try {
            $user = User::find(auth()->user()->id);
            $user->update($request->except('_token'));

            DB::commit();

            return back();
        } catch (\Throwable $e) {
            DB::rollback();

            throw $e;
        }

    }
}

resources/views/dashboard/transactions/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Dashboard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Create transaction</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <section class="col-lg-12 connectedSortable">

                        <div class="card direct-chat direct-chat-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create one transaction</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fas fa-minus"></i></button>
                                    {{--Remove--}}
                                    {{--<button type="button" class="btn btn-tool" data-widget="remove"><i class="fas fa-times"></i></button>--}}
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-3">
                                <form role="form" method="post" action="{{ route('transactions.store') }}">
                                    @csrf
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="from_email">Email кореспондента</label>
                                            <input type="email" class="form-control" id="from_email" name="from_email" placeholder="Enter email" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="date_done">Дата платежа</label>
                                            <input type="text" class="form-control" id="date_done" name="date_done" placeholder="dd-mm-yyyy h:i" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="number_purse">Номер кошелька</label>
                                            <input type="text" class="form-control" id="number_purse" name="number_purse" placeholder="Number purse" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="amount">Сумма</label>
                                            <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="input">Тип операции</label>
                                            <select class="custom-select" id="input" name="input" required>
                                                <option value="0">Вивод</option>
                                                <option value="1">Начисление</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="comment">Примечание</label>
                                            <input type="text" class="form-control" id="comment" name="comment" placeholder="Comment" required>
                                        </div>
                                        <div class="form-check">
                                            <input type="hidden" name="status" value="0" class="form-check-input" id="exampleCheck1">
                                            <input type="checkbox" name="status" value="1" class="form-check-input" id="status">
                                            <label class="form-check-label" for="status">Status active?</label>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>

                        <div class="card direct-chat direct-chat-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create transaction for range</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fas fa-minus"></i></button>
                                    {{--Remove--}}
                                    {{--<button type="button" class="btn btn-tool" data-widget="remove"><i class="fas fa-times"></i></button>--}}
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-3">
                                <form role="form" method="post" action="{{ route('transactions.store') }}">
                                    @csrf
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="from_email">Email кореспондента</label>
                                            <input type="email" class="form-control" id="from_email" name="from_email" placeholder="Enter email" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="date_from">Период начисления платежа с:</label>
                                            <input type="text" class="form-control" id="date_from" name="date_from" placeholder="dd-mm-yyyy" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="date_to">Период начисления платежа по:</label>
                                            <input type="text" class="form-control" id="date_to" name="date_to" placeholder="dd-mm-yyyy" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="time">Время начисления платежа по:</label>
                                            <input type="text" class="form-control" id="time" name="time" placeholder="H:i" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="number_purse">Номер кошелька</label>
                                            <input type="text" class="form-control" id="number_purse" name="number_purse" placeholder="Number purse" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="amount">Сумма</label>
                                            <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="input">Тип операции</label>
                                            <select class="custom-select" id="input" name="input" required>
                                                <option value="0">Вивод</option>
                                                <option value="1">Начисление</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="comment">Примечание</label>
                                            <input type="text" class="form-control" id="comment" name="comment" placeholder="Comment" required>
                                        </div>
                                        <div class="form-check">
                                            <input type="hidden" name="status" value="0" class="form-check-input" id="exampleCheck1">
                                            <input type="checkbox" name="status" value="1" class="form-check-input" id="status">
                                            <label class="form-check-label" for="status">Status active?</label>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </section>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/dashboard/transactions/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Dashboard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Edit transaction</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <section class="col-lg-12 connectedSortable">

                        <div class="card direct-chat direct-chat-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit transaction</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fas fa-minus"></i></button>
                                    {{--Remove--}}
                                    {{--<button type="button" class="btn btn-tool" data-widget="remove"><i class="fas fa-times"></i></button>--}}
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-3">
                                <form role="form" method="post" action="{{ route('transactions.update', $payment->id) }}">
                                    @method('PUT')
                                    @csrf
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="from_email">Email кореспондента</label>
                                            <input type="email" class="form-control" id="from_email" name="from_email" placeholder="Enter email" value="{{$payment->from_email}}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="date_done">Дата платежа</label>
                                            <input type="text" class="form-control" id="date_done" name="date_done" placeholder="dd-mm-yyyy h:i" value="{{\Carbon\Carbon::parse($payment->date_done)->format('d-m-Y H:i')}}" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="number_purse">Номер кошелька</label>
                                            <input type="text" class="form-control" id="number_purse" name="number_purse" value="{{$payment->number_purse}}" placeholder="Number purse" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="amount">Сумма</label>
                                            <input type="text" class="form-control" id="amount" name="amount" value="{{$payment->amount}}" placeholder="Amount" required>
                                        </div>
                                        <div class="form-group">
                                            <label for="input">Тип операции</label>
                                            <select class="custom-select" id="input" name="input" required>
                                                <option value="0" {{$payment->input == 0 ? 'selected' : ''}}>Вивод</option>
                                                <option value="1" {{$payment->input == 1 ? 'selected' : ''}}>Начисление</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label for="comment">Примечание</label>
                                            <input type="text" class="form-control" id="comment" name="comment" placeholder="Comment" required>
                                        </div>
                                        <div class="form-check">
                                            <input type="hidden" name="status" value="0" {{$payment->status == 0 ? 'checked' : ''}} class="form-check-input" id="exampleCheck1">
                                            <input type="checkbox" name="status" value="1" {{$payment->status == 1 ? 'checked' : ''}} class="form-check-input" id="status">
                                            <label class="form-check-label" for="status">Status active?</label>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->

                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </form>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </section>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/dashboard/transactions/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Dashboard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Transactions</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <section class="col-lg-12 connectedSortable">

                        <div class="card direct-chat direct-chat-primary">
                            <div class="card-header">
                                <h3 class="card-title">Transactions</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fas fa-minus"></i></button>
                                    {{--Remove--}}
                                    {{--<button type="button" class="btn btn-tool" data-widget="remove"><i class="fas fa-times"></i></button>--}}
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">ДАТА</th>
                                        <th scope="col">ТИП ОПЕРАЦИИ</th>
                                        <th scope="col">КОРРЕСПОНДЕНТ</th>
                                        <th scope="col">СУММА</th>
                                        <th scope="col" colspan="2"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(count($transactions) > 0 )
                                        @foreach($transactions as $transaction)
                                        <tr>
                                            <th scope="row">{{\Carbon\Carbon::parse($transaction->date_done)->format('d-m-Y H:i')}}</th>
                                            <td>{{$transaction->type_operation == 0 ? 'Внутренняя транзакция' : 'Інша'}}</td>
                                            <td>{{$transaction->number_purse}}</td>
                                            <td>{{$transaction->input == 0 ? '-' : ''}}{{$transaction->amount}}</td>
                                            <td><a href="{{ route('transactions.edit', ['payment' => $transaction->id]) }}">Edit</a></td>
                                            <td>
                                                <form method="post" action="{{route('transactions.destroy', ['id' => $transaction->id])}}">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                    @else
                                        <tr>
                                            <th scope="row" colspan="6">Нет доступных транзакций</th>
                                        </tr>
                                    @endif
                                    </tbody>
                                </table>
                                <div>
                                    {{$transactions->links()}}
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>

                    </section>
                </div>
            </div>
        </section>
    </div>

@endsection